apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: mailbox-service.oss-k8s-security.cloudsec.training
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mailbox-service
            port:
              number: 80
  - host: server-health.oss-k8s-security.cloudsec.training
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: server-health
            port:
              number: 80
  - host: connectivity-check.oss-k8s-security.cloudsec.training
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: connectivity-check
            port:
              number: 80
